export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const GET_PRODUCTOS = 'GET_PRODUCTOS';
export const GET_PRODUCTOS_EXITO = 'GET_PRODUCTOS_EXITO';
export const GET_PRODUCTOS_ERROR = 'GET_PRODUCTOS_ERROR';
